# TCP-stack TEST CONFIGURATION

global:
    # result of each test will be in separate file in this folder
    test_result_dir: /tmp/vppqa
    log_dir: /tmp/vcl_results
    # IP address used in tests:
    # Configured on VPP loopback interface
    # Used as binding for iperf3 server listener
    host: 192.168.5.5
vpp:
    # can be overriden by --no-vpp argument
    enable: True
    # VPP binary:
    # Build location is *vpp git root*/build-root/install-vpp-native/vpp/bin/vpp
    # Install location is: /usr/bin/vpp OR /usr/local/bin/vpp
    binary: /usr/bin/vpp
    # startup_conf: VPP startup configuration file, install location is:
    # /etc/vpp/startup.conf
    startup_conf: /etc/vpp/startup.conf

vcllib:
    path: /home/sam/libvcl_ldpreload.so

# IPERF3 TEST CONFIGURATION
iperf3:
    # run test True/False
    enable: True

    # host on which server is running

    # each iperf session (client server instances) needs unique port
    # port num will increment for each session, starting at default_port
    # script will skip ports in use

    default_port: 1024

    # number of client-server instances

    sessions: 8

    # number of connections per client

    connections_per_session: 1

    # time (seconds) after which client will terminate
    # the first 10 seconds will not be measured

    test_duration: 30

    # Size of send/receive buffers and of messages sent

    message_size: 128KB

    # additional time, to allow clients to terminate. After this timeout expires,
    # all running instances will be terminated/killed

    additional_timeout: 20
